# Generated by Django 3.1.2 on 2020-10-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Entry Task Blog', max_length=255),
        ),
    ]
