# Generated by Django 3.1.2 on 2020-10-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='category',
        ),
    ]
